### ISSUE TITLE
Automule not working

### ISSUE THREAD

**Issue by peters0908** [SetupSonic/d2bot-with-kolbot-sonic#1]
Hi, just tried Sonic version Autosmurf and it work wonderful! But when bot full, it stop and call up Automule profile, but new mule game stay on begin login screen (the screen to choose BattleNet or Single) and no any action. Then D2Bot console says "No response from mule profile" and Mule Game stop. But bot will continue move on to new game but it won't pick anything since it's full. So Automule trigger again minutes later but still no mule. 

I've been use kolbot's AutoMule and it work without issue. So I just try the same way to config Sonic's AutoMule but no luck. It's me misunderstand something on setting AutoMule?

**Comment by anarchyx99x** [comment]
> Hi, just tried Sonic version Autosmurf and it work wonderful! But when bot full, it stop and call up Automule profile, but new mule game stay on begin login screen (the screen to choose BattleNet or Single) and no any action. Then D2Bot console says "No response from mule profile" and Mule Game stop. But bot will continue move on to new game but it won't pick anything since it's full. So Automule trigger again minutes later but still no mule.
> 
> I've been use kolbot's AutoMule and it work without issue. So I just try the same way to config Sonic's AutoMule but no luck. It's me misunderstand something on setting AutoMule?

Having the exact same issue, if anyone has a solution please share! <3

**Comment by hybrid2k17** [comment]
try adding -skiptobnet on your mule profile parameters

**Comment by SetupSonic** [comment]
Fixed in this commit: https://github.com/SetupSonic/d2bot-with-kolbot-sonic/commit/b2ebed84b87d320896d13b5065ef7648cc7b6eb2

Closing, let me know if you still have problems.
