### ISSUE TITLE
Error message: item.getstatex is not a function

### ISSUE THREAD

**Issue by LAeRacing** [SetupSonic/d2bot-with-kolbot-sonic#9]
`20:28:31 (sonic) ÿc1Pickit Tier (Tier) error! Line # ÿc243 ÿc1Entry: ÿc0[type] == shield && [flag] != ethereal && [Quality] <= magic && [flag] != runeword # [itemchargedskill] >= 0 # [tier] == /*fr+cr+lr*/((item.getStatEx(39) + item.getStatEx(41) + item.getStatEx(43)) * 10000) + /*str+dex+vita*/((item.getStatEx(0) + item.getStatEx(2) + item.getStatEx(3)) * 1000) + /*fbr+ctb*/((item.getStatEx(102) + item.getStatEx(20)) * 100) + /*defense*/(item.getStatEx(31) * 1) (expansion_sorc.nip) Error message: item.getstatex is not a function`

**This error is displayed every time, such a item is picked up.**
The **sorc quits game, when the inv is full**. On the next game, the **items are NOT sold to npc**.
So **keep getting exit game, cause inv is full and this error message appears** every time.

![Unbenannt](https://user-images.githubusercontent.com/38850969/78062493-0df68a00-738f-11ea-8609-846ab902e070.PNG)

**Comment by loomy18** [comment]
How did you resolve this?  I am trying to use the weighted tiers in a non-sonic kolbot installation and I am running into this error as well.

**Comment by blinktenor** [comment]
Copying over NTItemParser from sonic fixes this issue.
